# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ff592b81b2bcd5640531a009dc8a279b615fe9c7c5bfb0fee1506b113c37df58c743765d60a32568789cc0123d1e748c2367f490ac203ca75fbf5eb563aa6c

test:
  secret_key_base: faa5325f4d55a2fe5e4d8ae76977910763015b7c1f1c7aa747deb4e2a37b57c92a0ea6d9a685f61322dfb440908d218978f73eb55f2c5751bc7dee04046415a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
